# Generated by Django 5.0.2 on 2024-02-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.BigIntegerField(null=True)),
                ('objectid', models.BigIntegerField(null=True)),
                ('area', models.FloatField(null=True)),
                ('perimeter', models.FloatField(null=True)),
                ('ccode', models.CharField(max_length=18, null=True)),
                ('taluka', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('village', models.CharField(max_length=50, null=True)),
                ('remark', models.CharField(max_length=50, null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
            ],
        ),
    ]
