# Generated by Django 5.0.2 on 2024-05-09 10:06

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolygonData',
        ),
        migrations.DeleteModel(
            name='Villages',
        ),
        migrations.AddField(
            model_name='photo',
            name='feature',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
        migrations.AddField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
