# Generated by Django 5.0.2 on 2024-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_photo_polygondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_data',
            field=models.BinaryField(default=b'default_image_data'),
        ),
    ]
